In [1]:
import pandas as pd
wslist=['A','A','A','C','C','C','D','D','D']
columnlist=["編號","根冠1","根冠2","根冠3","根冠4","葉片數","中間葉長","中間葉寬","左邊葉長","左邊葉寬","葉面積(mm2)","第幾葉","炭疽級數","葉枯級數"]
for i in range(len(wslist)):
    #為了等下轉置，不讀取第一行做為表頭
    df_temp=pd.read_excel('raw_data/草莓田間數據-2021.8.16.xlsx',sheet_name=i,header=None)
    #轉置
    df_temp=df_temp.T
    #去掉多餘的資訊
    df_temp=df_temp.iloc[:,:14]
    #設定欄位
    df_temp.columns=columnlist
    #去除第一行
    df_temp=df_temp.drop(df_temp.index[0])
    
    #定義欄位格式
    for index,x in enumerate(columnlist):
        if index==5 or index==11:                    #當是葉片數和第幾葉時，要轉成整數
            for n in range(len(df_temp[x])):
                if df_temp[x].notnull().iloc[n]==True:
                    df_temp.iloc[n,index]=int(df_temp.iloc[n,index])
        elif index==6 or index==7 or index==8 or index==9 or index==10:    #當是葉長、葉寬相關資訊時，要四捨五入數
            for n in range(len(df_temp[x])):
                if df_temp[x].notnull().iloc[n]==True:
                    df_temp.iloc[n,index]=round(df_temp.iloc[n,index],2)
        elif index==0 or index==12 or index==13:    #編號、病害級數要轉整數
            df_temp[x]=df_temp[x].fillna(value=0)
            df_temp[x]=df_temp[x].astype("int16")
    
    #編號前加上處理的場域代號
    for n,x in enumerate(list(df_temp["編號"])):
        df_temp.iloc[n,0]=wslist[i]+str(x)
    
    #加入月份欄位
    month=[]
    for n in range(len(df_temp["編號"])):
        month.append('Aug')
    df_temp.insert(14,column="時間",value=month)
    if i ==0:
        df_Aug=df_temp.copy()
    else:
        df_Aug=df_Aug.append(df_temp)
len(df_Aug)

261

In [2]:
import pandas as pd
df_Aug_A_CK=pd.read_excel('raw_data/草莓田間數據-2021.8.16.xlsx',sheet_name=0,header=None)
df_Aug_A_CK

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,編號,1.0000,5.000000,11.000000,25.000000,26.000000,39.00000,43.000000,57.000000,68.000000,...,56.00,60.00,61.00,66.00,69.00,73.00,79.00,84.00,87.00,90.00
1,根冠1,4.8900,10.600000,14.640000,13.460000,13.570000,14.06000,10.740000,13.600000,16.830000,...,16.51,14.89,17.40,19.81,14.65,16.73,10.53,14.19,16.91,15.49
2,根冠2,13.3400,12.010000,18.030000,8.880000,14.300000,19.90000,17.870000,18.990000,8.980000,...,3.82,15.52,15.44,NaN,18.89,12.21,16.95,20.75,14.41,10.60
3,根冠3,9.5000,13.300000,NaN,NaN,NaN,NaN,NaN,NaN,18.130000,...,7.92,NaN,NaN,NaN,11.66,13.68,NaN,NaN,NaN,14.89
4,根冠4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,葉片數,6.0000,8.000000,5.000000,9.000000,7.000000,14.00000,7.000000,5.000000,7.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,中間葉長,72.2000,67.460000,64.780000,57.880000,64.550000,57.95000,61.690000,77.610000,54.620000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,中間葉寬,65.6500,66.800000,64.440000,57.400000,61.830000,57.43000,63.080000,75.200000,63.040000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,左邊葉長,68.7600,67.620000,56.240000,53.490000,64.440000,64.50000,67.280000,87.560000,63.850000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,左邊葉寬,57.1000,53.850000,51.850000,43.180000,47.860000,48.28000,55.870000,74.420000,52.040000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,葉面積(mm2),8844.9099,7794.076545,7206.608235,5362.799268,6628.573635,6003.22677,7394.890544,12390.844149,6098.891196,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,第幾葉,3.0000,3.000000,4.000000,4.000000,3.000000,3.00000,3.000000,2.000000,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,炭疽級數,0.0000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,葉枯級數,1.0000,0.000000,1.000000,0.000000,1.000000,0.00000,1.000000,1.000000,1.000000,...,0.00,0.00,1.00,0.00,1.00,0.00,1.00,1.00,0.00,0.00
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,葉枯級數：1 代表葉捲、葉背之邊緣紅紅的,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_Aug_A_CK=df_Aug_A_CK.T
df_Aug_A_CK

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數,NaN,葉枯級數：1 代表葉捲、葉背之邊緣紅紅的
1,1.0,4.89,13.34,9.5,NaN,6.0,72.2,65.65,68.76,57.1,8844.9099,3.0,0.0,1.0,NaN,NaN
2,5.0,10.6,12.01,13.3,NaN,8.0,67.46,66.8,67.62,53.85,7794.076545,3.0,0.0,0.0,NaN,NaN
3,11.0,14.64,18.03,NaN,NaN,5.0,64.78,64.44,56.24,51.85,7206.608235,4.0,0.0,1.0,NaN,NaN
4,25.0,13.46,8.88,NaN,NaN,9.0,57.88,57.4,53.49,43.18,5362.799268,4.0,0.0,0.0,NaN,NaN
5,26.0,13.57,14.3,NaN,NaN,7.0,64.55,61.83,64.44,47.86,6628.573635,3.0,0.0,1.0,NaN,NaN
6,39.0,14.06,19.9,NaN,NaN,14.0,57.95,57.43,64.5,48.28,6003.22677,3.0,0.0,0.0,NaN,NaN
7,43.0,10.74,17.87,NaN,NaN,7.0,61.69,63.08,67.28,55.87,7394.890544,3.0,0.0,1.0,NaN,NaN
8,57.0,13.6,18.99,NaN,NaN,5.0,77.61,75.2,87.56,74.42,12390.844149,2.0,0.0,1.0,NaN,NaN
9,68.0,16.83,8.98,18.13,NaN,7.0,54.62,63.04,63.85,52.04,6098.891196,2.0,0.0,1.0,NaN,NaN
10,77.0,14.43,17.29,8.82,11.93,12.0,58.45,57.71,58.46,52.03,6525.164258,3.0,0.0,0.0,NaN,NaN
11,86.0,9.43,4.49,22.54,NaN,7.0,75.33,81.16,78.46,72.81,11766.737308,3.0,0.0,1.0,NaN,NaN
12,10.0,15.08,15.97,10.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
13,18.0,14.85,22.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
14,19.0,16.08,11.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
15,32.0,20.53,21.84,11.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
16,33.0,13.27,14.27,10.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
17,34.0,6.93,9.73,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
18,51.0,14.95,20.61,11.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
19,54.0,17.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
20,56.0,16.51,3.82,7.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
21,60.0,14.89,15.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
22,61.0,17.4,15.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
23,66.0,19.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
24,69.0,14.65,18.89,11.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
25,73.0,16.73,12.21,13.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
26,79.0,10.53,16.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
27,84.0,14.19,20.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
28,87.0,16.91,14.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
29,90.0,15.49,10.6,14.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN

In [4]:
df_Aug_A_CK=df_Aug_A_CK.iloc[:,:14]
df_Aug_A_CK.columns=["編號","根冠1","根冠2","根冠3","根冠4","葉片數","中間葉長","中間葉寬","左邊葉長","左邊葉寬","葉面積(mm2)","第幾葉","炭疽級數","葉枯級數"]
df_Aug_A_CK=df_Aug_A_CK.drop(df_Aug_A_CK.index[0])
df_Aug_A_CK

,編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數
1,1.0,4.89,13.34,9.5,NaN,6.0,72.2,65.65,68.76,57.1,8844.9099,3.0,0.0,1.0
2,5.0,10.6,12.01,13.3,NaN,8.0,67.46,66.8,67.62,53.85,7794.076545,3.0,0.0,0.0
3,11.0,14.64,18.03,NaN,NaN,5.0,64.78,64.44,56.24,51.85,7206.608235,4.0,0.0,1.0
4,25.0,13.46,8.88,NaN,NaN,9.0,57.88,57.4,53.49,43.18,5362.799268,4.0,0.0,0.0
5,26.0,13.57,14.3,NaN,NaN,7.0,64.55,61.83,64.44,47.86,6628.573635,3.0,0.0,1.0
6,39.0,14.06,19.9,NaN,NaN,14.0,57.95,57.43,64.5,48.28,6003.22677,3.0,0.0,0.0
7,43.0,10.74,17.87,NaN,NaN,7.0,61.69,63.08,67.28,55.87,7394.890544,3.0,0.0,1.0
8,57.0,13.6,18.99,NaN,NaN,5.0,77.61,75.2,87.56,74.42,12390.844149,2.0,0.0,1.0
9,68.0,16.83,8.98,18.13,NaN,7.0,54.62,63.04,63.85,52.04,6098.891196,2.0,0.0,1.0
10,77.0,14.43,17.29,8.82,11.93,12.0,58.45,57.71,58.46,52.03,6525.164258,3.0,0.0,0.0
11,86.0,9.43,4.49,22.54,NaN,7.0,75.33,81.16,78.46,72.81,11766.737308,3.0,0.0,1.0
12,10.0,15.08,15.97,10.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
13,18.0,14.85,22.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
14,19.0,16.08,11.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
15,32.0,20.53,21.84,11.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
16,33.0,13.27,14.27,10.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
17,34.0,6.93,9.73,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
18,51.0,14.95,20.61,11.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
19,54.0,17.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
20,56.0,16.51,3.82,7.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
21,60.0,14.89,15.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
22,61.0,17.4,15.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
23,66.0,19.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
24,69.0,14.65,18.89,11.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
25,73.0,16.73,12.21,13.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
26,79.0,10.53,16.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
27,84.0,14.19,20.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
28,87.0,16.91,14.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
29,90.0,15.49,10.6,14.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [5]:
for i,x in enumerate(list(df_Aug_A_CK["編號"])):
    df_Aug_A_CK.iloc[i,0]="A"+str(x)
df_Aug_A_CK

,編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數
1,A1.0,4.89,13.34,9.5,NaN,6.0,72.2,65.65,68.76,57.1,8844.9099,3.0,0.0,1.0
2,A5.0,10.6,12.01,13.3,NaN,8.0,67.46,66.8,67.62,53.85,7794.076545,3.0,0.0,0.0
3,A11.0,14.64,18.03,NaN,NaN,5.0,64.78,64.44,56.24,51.85,7206.608235,4.0,0.0,1.0
4,A25.0,13.46,8.88,NaN,NaN,9.0,57.88,57.4,53.49,43.18,5362.799268,4.0,0.0,0.0
5,A26.0,13.57,14.3,NaN,NaN,7.0,64.55,61.83,64.44,47.86,6628.573635,3.0,0.0,1.0
6,A39.0,14.06,19.9,NaN,NaN,14.0,57.95,57.43,64.5,48.28,6003.22677,3.0,0.0,0.0
7,A43.0,10.74,17.87,NaN,NaN,7.0,61.69,63.08,67.28,55.87,7394.890544,3.0,0.0,1.0
8,A57.0,13.6,18.99,NaN,NaN,5.0,77.61,75.2,87.56,74.42,12390.844149,2.0,0.0,1.0
9,A68.0,16.83,8.98,18.13,NaN,7.0,54.62,63.04,63.85,52.04,6098.891196,2.0,0.0,1.0
10,A77.0,14.43,17.29,8.82,11.93,12.0,58.45,57.71,58.46,52.03,6525.164258,3.0,0.0,0.0
11,A86.0,9.43,4.49,22.54,NaN,7.0,75.33,81.16,78.46,72.81,11766.737308,3.0,0.0,1.0
12,A10.0,15.08,15.97,10.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
13,A18.0,14.85,22.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
14,A19.0,16.08,11.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
15,A32.0,20.53,21.84,11.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
16,A33.0,13.27,14.27,10.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
17,A34.0,6.93,9.73,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
18,A51.0,14.95,20.61,11.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
19,A54.0,17.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
20,A56.0,16.51,3.82,7.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
21,A60.0,14.89,15.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
22,A61.0,17.4,15.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
23,A66.0,19.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
24,A69.0,14.65,18.89,11.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
25,A73.0,16.73,12.21,13.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
26,A79.0,10.53,16.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
27,A84.0,14.19,20.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
28,A87.0,16.91,14.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
29,A90.0,15.49,10.6,14.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [6]:
month=[]
for i in range(len(df_Aug_A_CK["編號"])):
    month.append('Aug')
#print(len(month))
df_Aug_A_CK.insert(14,column="時間",value=month)
df_Aug_A_CK

,編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數,時間
1,A1.0,4.89,13.34,9.5,NaN,6.0,72.2,65.65,68.76,57.1,8844.9099,3.0,0.0,1.0,Aug
2,A5.0,10.6,12.01,13.3,NaN,8.0,67.46,66.8,67.62,53.85,7794.076545,3.0,0.0,0.0,Aug
3,A11.0,14.64,18.03,NaN,NaN,5.0,64.78,64.44,56.24,51.85,7206.608235,4.0,0.0,1.0,Aug
4,A25.0,13.46,8.88,NaN,NaN,9.0,57.88,57.4,53.49,43.18,5362.799268,4.0,0.0,0.0,Aug
5,A26.0,13.57,14.3,NaN,NaN,7.0,64.55,61.83,64.44,47.86,6628.573635,3.0,0.0,1.0,Aug
6,A39.0,14.06,19.9,NaN,NaN,14.0,57.95,57.43,64.5,48.28,6003.22677,3.0,0.0,0.0,Aug
7,A43.0,10.74,17.87,NaN,NaN,7.0,61.69,63.08,67.28,55.87,7394.890544,3.0,0.0,1.0,Aug
8,A57.0,13.6,18.99,NaN,NaN,5.0,77.61,75.2,87.56,74.42,12390.844149,2.0,0.0,1.0,Aug
9,A68.0,16.83,8.98,18.13,NaN,7.0,54.62,63.04,63.85,52.04,6098.891196,2.0,0.0,1.0,Aug
10,A77.0,14.43,17.29,8.82,11.93,12.0,58.45,57.71,58.46,52.03,6525.164258,3.0,0.0,0.0,Aug
11,A86.0,9.43,4.49,22.54,NaN,7.0,75.33,81.16,78.46,72.81,11766.737308,3.0,0.0,1.0,Aug
12,A10.0,15.08,15.97,10.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
13,A18.0,14.85,22.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
14,A19.0,16.08,11.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
15,A32.0,20.53,21.84,11.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
16,A33.0,13.27,14.27,10.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
17,A34.0,6.93,9.73,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
18,A51.0,14.95,20.61,11.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
19,A54.0,17.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug
20,A56.0,16.51,3.82,7.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug
21,A60.0,14.89,15.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug
22,A61.0,17.4,15.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
23,A66.0,19.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug
24,A69.0,14.65,18.89,11.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
25,A73.0,16.73,12.21,13.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug
26,A79.0,10.53,16.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
27,A84.0,14.19,20.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Aug
28,A87.0,16.91,14.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug
29,A90.0,15.49,10.6,14.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,Aug

In [7]:
df_Aug

,編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數,時間
1,A1,4.89,13.34,9.5,NaN,6,72.2,65.65,68.76,57.1,8844.91,3,0,1,Aug
2,A5,10.6,12.01,13.3,NaN,8,67.46,66.8,67.62,53.85,7794.08,3,0,0,Aug
3,A11,14.64,18.03,NaN,NaN,5,64.78,64.44,56.24,51.85,7206.61,4,0,1,Aug
4,A25,13.46,8.88,NaN,NaN,9,57.88,57.4,53.49,43.18,5362.8,4,0,0,Aug
5,A26,13.57,14.3,NaN,NaN,7,64.55,61.83,64.44,47.86,6628.57,3,0,1,Aug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,D76,11.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
27,D80,17.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
28,D81,10.38,10.41,12.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
29,D85,NaN,15.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
30,D89,NaN,14.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug

In [8]:
#連線資料庫
import pyodbc
server = 'localhost'
database = 'test'
username = 'yachu'
password = '{@o8853Lisa}'
driver= '{ODBC Driver 17 for SQL Server}'

with pyodbc.connect('DRIVER='+driver+';SERVER=tcp:'+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+
password) as conn:
    with conn.cursor() as cursor:
        sql='''CREATE TABLE [田間試驗八月](
        [編號] [varchar] NOT NULL,
        [根冠1] [float],
        [根冠2] [float],
        [根冠3] [float],
        [根冠4] [float],
        [葉片數] [int],
        [中間葉長] [float],
        [中間葉寬] [float],
        [左邊葉長] [float],
        [左邊葉寬] [float],
        [葉面積(mm2)] [float],
        [第幾葉] [int],
        [炭疽級數] [int],
        [葉枯級數] [int],
        [時間] [varchar]
        )
        '''
        cursor.execute(sql)

    conn.commit()
conn.close()

In [9]:
import pyodbc
server = 'localhost'
database = 'test'
username = 'yachu'
password = '{@o8853Lisa}'
driver= '{ODBC Driver 17 for SQL Server}'

with pyodbc.connect('DRIVER='+driver+';SERVER=tcp:'+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+
password) as conn:
    with conn.cursor() as cursor:
        for index, row in df_Aug.iterrows():
            cursor.execute("INSERT INTO 田間試驗八月 \
                           (編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數,時間) \
                           values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9],row[10],row[11],row[12],row[13],row[14])
    conn.commit()
conn.close()

ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]內送表格式資料流 (TDS) 遠端程序呼叫 (RPC) 通訊協定資料流不正確。參數 8 (""): 提供的值不是資料類型 float 的有效執行個體。請檢查無效值的來源資料。例如，無效值是具有小數位數大於有效位數的 numeric 類型資料。 (8023) (SQLExecDirectW)')

In [10]:
conn.close()

https://docs.microsoft.com/zh-tw/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-ver16

In [11]:
df_Aug

,編號,根冠1,根冠2,根冠3,根冠4,葉片數,中間葉長,中間葉寬,左邊葉長,左邊葉寬,葉面積(mm2),第幾葉,炭疽級數,葉枯級數,時間
1,A1,4.89,13.34,9.5,NaN,6,72.2,65.65,68.76,57.1,8844.91,3,0,1,Aug
2,A5,10.6,12.01,13.3,NaN,8,67.46,66.8,67.62,53.85,7794.08,3,0,0,Aug
3,A11,14.64,18.03,NaN,NaN,5,64.78,64.44,56.24,51.85,7206.61,4,0,1,Aug
4,A25,13.46,8.88,NaN,NaN,9,57.88,57.4,53.49,43.18,5362.8,4,0,0,Aug
5,A26,13.57,14.3,NaN,NaN,7,64.55,61.83,64.44,47.86,6628.57,3,0,1,Aug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,D76,11.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
27,D80,17.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
28,D81,10.38,10.41,12.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
29,D85,NaN,15.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug
30,D89,NaN,14.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Aug